apiVersion: v1
kind: Service
metadata:
  name: vault-service
spec:
  selector:
    app: vault
  ports:
  - name: vault-svc-port 
    port: {{ .Values.service.port }}
    protocol: TCP
    # should match with container, if non-provided defaults to selector port
    targetPort: {{ .Values.service.port }}

